version: '3.8'  # Use an appropriate version of Docker Compose

services:
  app:
    image: alpine:latest
    container_name: network_container
    command: tail -f /dev/null
    networks:
      010_vlan_net:
        priority: 500
      100_vlan_net:
        priority: 400
      200_vlan_net:
        priority: 300
      shared_bridge:
        priority: 1
    volumes:
      - ./vol:/data
    restart: always
    healthcheck:
      # Check if the gateway (e.g., 192.168.1.1) is reachable
      test: ["CMD-SHELL", "${HEALTHCHECK_CMD}"]
      interval: ${HEALTHCHECK_INT}
      timeout: ${HEALTHCHECK_TOT}
      retries: ${HEALTHCHECK_RTS}
      start_period: ${HEALTHCHECK_STP}

networks:
  010_vlan_net:
    name: ${VLAN010_NAME}
    driver: macvlan
    driver_opts:
      com.docker.network.endpoint.ifname: ${VLAN010_ETH:-eth-010}
      parent: ${VLAN010_PARENT}
    ipam:
      config:
        - subnet: ${VLAN010_SUBNET}
          gateway: ${VLAN010_GATEWAY}
          ip_range: ${VLAN010_IPRANGE}
  100_vlan_net:
    name: ${VLAN100_NAME}
    driver: macvlan
    driver_opts:
      com.docker.network.endpoint.ifname: ${VLAN100_ETH:-eth-100}
      parent: ${VLAN100_PARENT}
    ipam:
      config:
        - subnet: ${VLAN100_SUBNET}
          gateway: ${VLAN100_GATEWAY}
          ip_range: ${VLAN100_IPRANGE}
  200_vlan_net:
    name: ${VLAN200_NAME}
    driver: macvlan
    driver_opts:
      com.docker.network.endpoint.ifname: ${VLAN200_ETH:-eth-200}
      parent: ${VLAN200_PARENT}
    ipam:
      config:
        - subnet: ${VLAN200_SUBNET}
          gateway: ${VLAN200_GATEWAY}
          ip_range: ${VLAN200_IPRANGE}
  shared_bridge:
    name: ${BRIDGE_NAME}
    driver: bridge
    driver_opts:
      com.docker.network.endpoint.ifname: ${BRIDGE_ETH:-eth-shared}
