services:
  app:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME:-network-container}
    hostname: ${HOSTNAME:-network-container}
    command: tail -f /dev/null    
    restart: always
    networks:
      010_vlan_net:
        interface_name: ${VLAN010_ETH}
      100_vlan_net:
        interface_name: ${VLAN100_ETH}
      200_vlan_net:
        interface_name: ${VLAN200_ETH}
      shared_bridge:
        interface_name: ${BRIDGE_ETH}
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - NET_BROADCAST
    volumes:
      - ${VOLUME_NAME:-./vol/data/}:/data/:rw
    healthcheck:
      # Check if the gateway (e.g., 192.168.1.1) is reachable
      test: ["CMD-SHELL", "${HEALTHCHECK_CMD}"]
      interval: ${HEALTHCHECK_INT}
      timeout: ${HEALTHCHECK_TOT}
      retries: ${HEALTHCHECK_RTS}
      start_period: ${HEALTHCHECK_STP}
  keepalived:
    env_file:
      - ./config/docker-keepalived.env
    build:
      context: .
      dockerfile: Dockerfile.armv7
    image: ${KA_IMAGE}
    container_name: ${KA_CONTAINER_NAME:-keepalived}
    # hostname: ${KA_HOST_NAME:-keepalived}
    restart: always
    depends_on:
      app:
        condition: service_healthy
    environment:
      KEEPALIVED_OPTS: "${KA_OPTS:--n -l -D -f /usr/local/etc/keepalived/keepalived.conf}"
      KEEPALIVED_LOG_FILE: "${KA_LOG_FILE:-/var/log/keepalived/keepalived.log}"
      LOGROTATE_INTERVAL: "${KA_LOGROTATE_INTERVAL:-86400}"
      LOGROTATE_ROTATE: "${KA_LOGROTATE_ROTATE:-7}"
      LOGROTATE_COMPRESS: "${KA_LOGROTATE_COMPRESS:-true}"
    # Define the healthcheck to perform.
    healthcheck:
      test:
        - "CMD-SHELL"
        - ${KA_HEALTHCHECK_CMD:-nslookup google.com}
      interval: ${KA_HEALTHCHECK_INT:-30s}
      timeout: ${KA_HEALTHCHECK_TOT:-10s}
      retries: ${KA_HEALTHCHECK_RTS:-3}
      start_period: ${KA_HEALTHCHECK_STP:-30s}
    # Joins the network namespace
    network_mode: "service:app"
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - NET_BROADCAST
    volumes:
      - ${KA_VOL_CFG:-./vol/keepalived/keepalived.conf}:/usr/local/etc/keepalived/keepalived.conf:ro
      - ${KA_VOL_LOG:-./vol/keepalived/log/}:/var/log/keepalived/:rw

networks:
  010_vlan_net:
    name: ${VLAN010_NAME}
    driver: macvlan
    driver_opts:
      parent: ${VLAN010_PARENT}
    ipam:
      config:
        - subnet: ${VLAN010_SUBNET}
          gateway: ${VLAN010_GATEWAY}
          ip_range: ${VLAN010_IPRANGE}
  100_vlan_net:
    name: ${VLAN100_NAME}
    driver: macvlan
    driver_opts:
      parent: ${VLAN100_PARENT}
    ipam:
      config:
        - subnet: ${VLAN100_SUBNET}
          gateway: ${VLAN100_GATEWAY}
          ip_range: ${VLAN100_IPRANGE}
  200_vlan_net:
    name: ${VLAN200_NAME}
    driver: macvlan
    driver_opts:
      parent: ${VLAN200_PARENT}
    ipam:
      config:
        - subnet: ${VLAN200_SUBNET}
          gateway: ${VLAN200_GATEWAY}
          ip_range: ${VLAN200_IPRANGE}
  shared_bridge:
    name: ${BRIDGE_NAME}
    driver: bridge
    driver_opts: {}
